name: Run Project in Docker

on:
  push:
    branches:
      - main

jobs:
  run_in_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0  # Updated to a newer version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install
      
      - name: Run Playwright API Tests
        run: npm run apiSuite

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: playwright-report

      - name: Debug Docker Build Context
        run: |
            ls -al  # List files in the current directory
            cat Dockerfile  # Display the contents of the Dockerfile
  
      - name: Debug Docker Build
        run: |
            docker build -t mayank9tee/playwright-github-mt:latest .
        
      - name: Debug Docker Image List
        run: |
            docker images
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: mayank9tee/playwright-github-mt:latest