name: Playwright Test

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LOCAL_EXECUTION: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: Run Playwright UI Tests
        run: npm run uiSuite
      
      - name: Run Playwright API Tests
        run: npm run apiSuite
       
      - name: Generate playwright test report
        run: npm run generate-report

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: playwight-report
          path: playwight-report